name: cppcheck

run-name: Cppcheck

on: [push]

env:
  SRC_CODE: PIO-IRQ/src/main.c

jobs:
  pio_cppcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install cppcheck
        run: |
          sudo apt install cppcheck

      - name: run cppcheck
        run: |
          cppcheck -iASF -ioled --enable=all --suppress=shiftTooManyBitsSigned --suppress=missingIncludeSystem --suppress=integerOverflow --suppress=unmatchedSuppression --suppress=unusedFunction --error-exitcode=2 ${SRC_CODE}
